# Generated by Django 5.0 on 2023-12-21 12:02

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Email address has already token"},
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="nickname",
            ),
        ),
    ]
