# Generated by Django 5.0 on 2023-12-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="コメント"),
        ),
    ]
