# Generated by Django 5.0 on 2023-12-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名前")),
                ("text", models.CharField(max_length=256, verbose_name="本文")),
                ("image", models.CharField(max_length=512, verbose_name="画像URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="投稿日時"),
                ),
            ],
            options={
                "db_table": "tweets",
            },
        ),
    ]
