# Generated by Django 5.0 on 2023-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="image",
            field=models.CharField(blank=True, max_length=512, verbose_name="画像URL"),
        ),
    ]
