# Generated by Django 5.0 on 2023-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0002_alter_tweet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="image",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="画像URL"
            ),
        ),
    ]
