# Generated by Django 5.0 on 2023-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0003_alter_tweet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.TextField(verbose_name="本文"),
        ),
    ]
